stages:
  Status:
    actions:
    - type: liquibase
      command: status

  Update:
    actions:
    - type: liquibase
      # if: "${LBCOMMAND} == update"
      command: update-testing-rollback

endStage:
  actions:
  - type: liquibase
    command: history
  # - type: liquibase
  #   command: drop-all